# Generated by Django 2.2.5 on 2020-02-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20200203_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(choices=[('1', 'Student Coordinator'), ('2', 'Secretary'), ('3', 'Team Head'), ('4', 'Ex-Officio')])),
                ('position', models.CharField(choices=[('SC', 'Student Coordinator'), ('PRE', 'President'), ('SEC', 'Secretary'), ('SEC1', 'Secretary:Internal Affairs'), ('SEC2', 'Secretary:All-Year Talks'), ('SEC3', 'Secretary:Fests'), ('COMM', 'Communications Team Head'), ('CONTENT', 'Content and Online Publicity Team Head'), ('TECH', 'Tech Team Head'), ('EVE', 'Events Management Team Head'), ('EX', 'Ex-Officio')], max_length=264)),
                ('name', models.CharField(max_length=264)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
