# Generated by Django 2.2.5 on 2020-02-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_memberinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='rank',
            field=models.CharField(choices=[('1', 'Student Coordinator'), ('2', 'Secretary'), ('3', 'Team Head'), ('4', 'Ex-Officio')], max_length=264),
        ),
    ]
