# Generated by Django 2.2.5 on 2020-02-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20200203_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='rank',
            field=models.CharField(choices=[('1', 'Student Coordinator'), ('2', 'President'), ('3', 'Secretary'), ('4', 'Team Head'), ('5', 'Ex-Officio')], max_length=264),
        ),
    ]
