# Generated by Django 2.2.5 on 2020-03-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20200203_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=264)),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('topic', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='ResourcePerson',
            fields=[
                ('resourcePerson_ID', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('BIO', 'Biological Sciences'), ('CHE', 'Chemical'), ('CHEM', 'Chemistry'), ('CE', 'Civil'), ('CS', 'Computer Science'), ('EEE', 'Electical and Electronics'), ('ECON', 'Economics and Finances'), ('HSS', 'Humanities and Social Sciences'), ('MATH', 'Mathematics'), ('ME', 'Mechanical'), ('PHA', 'Pharmacy'), ('PHY', 'Physics'), ('BITS', 'Other')], max_length=264)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=264)),
            ],
        ),
        migrations.DeleteModel(
            name='LectureInfo',
        ),
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.ManyToManyField(blank=True, to='basic_app.ResourcePerson'),
        ),
    ]
