# Generated by Django 2.2.5 on 2020-03-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20200312_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expenseID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(max_length=264)),
                ('date', models.DateField()),
                ('expenditure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Event')),
            ],
        ),
    ]
