# Generated by Django 2.2.5 on 2020-02-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20200203_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='lec_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
