# Generated by Django 2.2.5 on 2020-03-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20200312_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.ManyToManyField(to='basic_app.ResourcePerson'),
        ),
    ]
